# Generated by Django 6.0.5 on 2026-05-21 23:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import website.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "image",
                    models.ImageField(
                        height_field="height", upload_to="logos/", width_field="width"
                    ),
                ),
                (
                    "width",
                    models.PositiveSmallIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("qr_title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "qr_subtitle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100, unique=True)),
                (
                    "visible",
                    models.BooleanField(
                        default=True, help_text="Set to False to hide this word in maps"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeafletProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The short name to use with provider.js",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="The url for a generic leaflet provider",
                        max_length=150,
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("name__isnull", False),
                            ("url__isnull", False),
                            _connector="OR",
                        ),
                        name="either_name_or_url_not_null",
                        violation_error_message="Either name or url should be set to a valid value",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Landscape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "domain",
                    models.URLField(
                        blank=True,
                        help_text="Domain in showcase page. Leave blank to use the one in .env",
                    ),
                ),
                ("default", website.fields.UniqueBooleanField(default=False)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to hide it in views, unless is chosen as default",
                    ),
                ),
                (
                    "reload_time",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Reload time (in seconds) for showcase page",
                    ),
                ),
                ("zoom_initial", models.PositiveSmallIntegerField(default=15)),
                ("zoom_min", models.PositiveSmallIntegerField(default=13)),
                ("zoom_max", models.PositiveSmallIntegerField(default=20)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="The map provider to use with leaflet map",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.leafletprovider",
                    ),
                ),
                (
                    "logo_event",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.logo",
                    ),
                ),
                (
                    "logo_organizer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.logo",
                    ),
                ),
                (
                    "logo_partners",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="website.logo"
                    ),
                ),
                ("places", models.ManyToManyField(blank=True, to="website.place")),
            ],
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("message", models.TextField(max_length=500)),
                (
                    "landscape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.landscape",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to="website.place",
                    ),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True, related_name="shares", to="website.word"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WordFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.PositiveIntegerField(default=0)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_frequencies",
                        to="website.place",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_frequencies",
                        to="website.word",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Word Frequencies",
                "ordering": ("-frequency",),
            },
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.CheckConstraint(
                condition=models.Q(("zoom_min__lte", models.F("zoom_initial"))),
                name="zoom_min <= zoom_initial",
            ),
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.CheckConstraint(
                condition=models.Q(("zoom_max__gte", models.F("zoom_initial"))),
                name="zoom_max >= zoom_initial",
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("location__isnull", False),
                    models.Q(("x__isnull", False), ("y__isnull", False)),
                    _connector="OR",
                ),
                name="location_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="wordfrequency",
            constraint=models.UniqueConstraint(
                fields=("word", "place"), name="WordFrequency uniqueness"
            ),
        ),
    ]
