# Generated by Django 6.0.5 on 2026-05-22 03:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import website.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "default",
                    website.fields.UniqueBooleanField(
                        default=False,
                        help_text="If selected this is the default map to show for this landscape",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to hide it in views, ignore if default=True",
                    ),
                ),
                ("zoom_initial", models.PositiveSmallIntegerField(default=15)),
                ("zoom_min", models.PositiveSmallIntegerField(default=13)),
                ("zoom_max", models.PositiveSmallIntegerField(default=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="landscape",
            name="zoom_min <= zoom_initial",
        ),
        migrations.RemoveConstraint(
            model_name="landscape",
            name="zoom_max >= zoom_initial",
        ),
        migrations.AlterField(
            model_name="landscape",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Set to False to hide it in views, ignore if default=True",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="landscape",
            field=models.ForeignKey(
                help_text="The landscape this map belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maps",
                to="website.landscape",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="places",
            field=models.ManyToManyField(blank=True, to="website.place"),
        ),
        migrations.RemoveField(
            model_name="landscape",
            name="location",
        ),
        migrations.RemoveField(
            model_name="landscape",
            name="places",
        ),
        migrations.RemoveField(
            model_name="landscape",
            name="x",
        ),
        migrations.RemoveField(
            model_name="landscape",
            name="y",
        ),
        migrations.RemoveField(
            model_name="landscape",
            name="zoom_initial",
        ),
        migrations.RemoveField(
            model_name="landscape",
            name="zoom_max",
        ),
        migrations.RemoveField(
            model_name="landscape",
            name="zoom_min",
        ),
        migrations.AddConstraint(
            model_name="map",
            constraint=models.CheckConstraint(
                condition=models.Q(("zoom_min__lte", models.F("zoom_initial"))),
                name="zoom_min <= zoom_initial",
            ),
        ),
        migrations.AddConstraint(
            model_name="map",
            constraint=models.CheckConstraint(
                condition=models.Q(("zoom_max__gte", models.F("zoom_initial"))),
                name="zoom_max >= zoom_initial",
            ),
        ),
    ]
