# Generated by Django 5.2 on 2026-05-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landscape",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="The map provider to use with leaflet map",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="website.leafletprovider",
            ),
        ),
    ]
