# Generated by Django 6.0.5 on 2026-05-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_map_remove_landscape_zoom_min_zoom_initial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="overlay",
            field=models.ImageField(blank=True, null=True, upload_to="overlays/"),
        ),
    ]
