# Generated by Django 6.0.5 on 2026-05-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_landscape_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="qr_subtitle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="qr_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
