# Generated by Django 6.0.5 on 2026-05-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_map_overlay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="places",
            field=models.ManyToManyField(
                blank=True, related_name="maps", to="website.place"
            ),
        ),
    ]
