version: "3.8"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
        
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: landscapes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lv-password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - "54320:5432"
      
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - app
        
  app:
    build: .
    command: gunicorn --workers=3 --bind 0.0.0.0:8000 admin.wsgi
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgis://postgres:lv-password@db:5432/landscapes
    depends_on:
      - db
        
volumes:
  postgres_data: