version: "3"

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: landscapes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lv-password
    ports:
      - "54320:5432"
        
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
        
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgis://postgres:lv-password@db:5432/landscapes
    depends_on:
      - db
    # command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/code