[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["voices"]

[project]
name = "voice-landscape"
version = "0.1.1"
requires-python = ">=3.10"
dependencies = [
    "django>=4",
    "django-compressor",
    "django-cors-headers",
    "django-extensions",
    "django-jazzmin",
    "django-sass-processor",
    "libsass", 
    "loguru",
    "python-decouple",
    
    "pydub",
    "pocketsphinx",
    "SpeechRecognition",

    "spacy",
]

[project.optional-dependencies]
prod = ["gunicorn"]
dev = ["black", "isort"]
test = ["pytest", "httpx"]

[tool.isort]
profile = "black"