[project]
name = "voice-landscape"
version = "0.9.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "loguru>=0.7.3",
    "numpy>=2.4.6",
    "pillow>=12.2.0",
    "python-dotenv>=1.2.2",
    "spacy>=3.8.14",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.3.0",
    "django-types>=0.24.0",
]
lab = [
    "marimo>=0.23.6",
    "polars>=1.40.1",
]
prod = [
    "gunicorn>=26.0.0",
]
