[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["voices"]

[project]
name = "voice-landscape"
version = "0.3.0"
requires-python = ">=3.10"
dependencies = [
    "django>=4",
    "django-compressor",
    "django-cors-headers",
    "django-extensions",
    "django-jazzmin",
    "django-sass-processor",
    "dj-database-url",
    "gunicorn",
    "jupyterlab",
    "libsass",
    "loguru",
    "pydub",
    "psycopg2",
    "python-decouple",
    "spacy",
    "SpeechRecognition",
    "tqdm",
]

[project.optional-dependencies]
dev = ["black", "ipython", "isort", "pip-tools"]
test = ["pytest", "httpx"]

[tool.isort]
profile = "black"