[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["voices"]

[project]
name = "voice-landscape"
version = "0.1.1"
requires-python = ">=3.10"
dependencies = [
    "django>=4",
    "django-jazzmin",
    "loguru",
    "python-decouple",
    
    "geopy",
    "pydub",
    "spacy",
    "SpeechRecognition",
    
    "databases",
    "databases[sqlite]",
    "databases[postgresql]",
    "fastapi",
    "jinja2",
    "pydantic",
    "python-multipart",
    "sqladmin==0.7.0",
    "sqlmodel",
    "starlette",
    "uvicorn",
    "libsass",
]

[project.optional-dependencies]
prod = ["gunicorn"]
dev = ["black", "isort"]
test = ["pytest", "httpx"]

[tool.isort]
profile = "black"