# Generated by Django 4.1.7 on 2023-03-13 23:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
    ]
