# Generated by Django 4.1.7 on 2023-03-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_landscape"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="landscape",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
