# Generated by Django 4.1.7 on 2023-03-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_place_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordfrequency",
            name="frequency",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
