# Generated by Django 4.1.7 on 2023-03-14 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_place_wordfrequency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordfrequency",
            options={"verbose_name_plural": "Word Frequencies"},
        ),
    ]
