# Generated by Django 4.1.7 on 2023-03-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_wordfrequency_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordfrequency",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_frequencies",
                to="website.place",
            ),
        ),
    ]
