# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: landscapes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lv-password
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
        
        
volumes:
  postgres_data: