# Generated by Django 4.1.7 on 2023-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_place_wordfrequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
