# Generated by Django 4.2.4 on 2023-08-18 20:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import apps.website.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_wordfrequency_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Landscape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("default", apps.website.fields.UniqueBooleanField(default=False)),
                (
                    "reload_time",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Reload time (in seconds) for showcase page",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("Stamen.TonerBackground", "Toner Background"),
                            ("Stamen.Toner", "Toner"),
                            ("Stamen.Terrain", "Terrain"),
                            ("Stamen.Watercolor", "Watercolor"),
                        ],
                        default="Stamen.TonerBackground",
                        help_text="The map provider to use with leaflet map",
                        max_length=100,
                    ),
                ),
                ("zoom_initial", models.PositiveSmallIntegerField(default=15)),
                ("zoom_min", models.PositiveSmallIntegerField(default=13)),
                ("zoom_max", models.PositiveSmallIntegerField(default=20)),
                ("places", models.ManyToManyField(blank=True, to="website.place")),
            ],
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.CheckConstraint(
                check=models.Q(("zoom_min__lte", models.F("zoom_initial"))),
                name="zoom_min <= zoom_initial",
            ),
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.CheckConstraint(
                check=models.Q(("zoom_max__gte", models.F("zoom_initial"))),
                name="zoom_max >= zoom_initial",
            ),
        ),
    ]
