# Generated by Django 4.2.4 on 2023-08-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_landscape"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100, unique=True)),
                (
                    "visible",
                    models.BooleanField(
                        default=True, help_text="Set to False to hide this word in maps"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="wordfrequency",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="place_frequencies",
                to="website.word",
            ),
        ),
    ]
