# Generated by Django 4.2.4 on 2023-08-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_landscape"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="reload_time",
            field=models.PositiveIntegerField(
                default=300, help_text="Reload time (in seconds) for showcase page"
            ),
        ),
    ]
