# Generated by Django 4.2.4 on 2023-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_landscape_reload_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="provider",
            field=models.CharField(
                choices=[
                    ("Stamen.TonerBackground", "Toner Background"),
                    ("Stamen.Toner", "Toner"),
                    ("Stamen.Terrain", "Terrain"),
                    ("Stamen.Watercolor", "Watercolor"),
                ],
                default="Stamen.TonerBackground",
                help_text="The map provider to use with leaflet map",
                max_length=100,
            ),
        ),
    ]
