# Generated by Django 4.2.4 on 2023-08-29 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_alter_share_landscape"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeafletProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The short name to use with provider.js",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="The url for a generic leaflet provider",
                        max_length=150,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="leafletprovider",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("name__isnull", False), ("url__isnull", False), _connector="OR"
                ),
                name="either_name_or_url_not_null",
                violation_error_message=(
                    "Either name or url should be set to a valid value"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="landscape",
            name="provider",
            field=models.ForeignKey(
                help_text="The map provider to use with leaflet map",
                on_delete=django.db.models.deletion.PROTECT,
                to="website.leafletprovider",
            ),
        ),
    ]
