# Generated by Django 4.2.4 on 2023-08-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_landscape_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="landscape",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="landscape",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
