# Generated by Django 4.2.4 on 2023-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_landscape_description_alter_landscape_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landscape",
            name="zoom_initial",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="landscape",
            name="zoom_max",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="landscape",
            name="zoom_min",
            field=models.PositiveSmallIntegerField(default=13),
        ),
    ]
