# Generated by Django 4.2.4 on 2023-08-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_landscape_zoom_initial_landscape_zoom_max_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.CheckConstraint(
                check=models.Q(("zoom_min__lte", models.F("zoom_initial"))),
                name="zoom_min <= zoom_initial",
            ),
        ),
        migrations.AddConstraint(
            model_name="landscape",
            constraint=models.CheckConstraint(
                check=models.Q(("zoom_max__gte", models.F("zoom_initial"))),
                name="zoom_max >= zoom_initial",
            ),
        ),
    ]
