# Generated by Django 4.2.5 on 2023-09-16 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_landscape_enabled_alter_landscape_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shares",
                to="website.place",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="words",
            field=models.ManyToManyField(
                blank=True, related_name="shares", to="website.word"
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
