# Generated by Django 4.2.5 on 2023-09-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_landscape_enabled_alter_landscape_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="words",
            field=models.ManyToManyField(
                blank=True, related_name="shares", to="website.word"
            ),
        ),
    ]
