# Generated by Django 4.2.5 on 2023-09-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_share_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="place",
                to="website.place",
            ),
        ),
    ]
