# Generated by Django 4.2.5 on 2023-09-16 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_share_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
