"""
Django settings for voices project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Callable, Optional

import spacy.symbols
from django.contrib.gis.geos import Point
from dotenv import load_dotenv

load_dotenv()


def env[T](
    name: str,
    default: Optional[T] = None,
    cast: Callable[[str], T] = str,
):
    value = os.getenv(name)

    if value is not None:
        return cast(value)

    if default is None:
        raise ValueError(
            f"No value specified for {name}, either set in .env or set a default"
        )

    return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
APP_PATH = Path(__file__).resolve().parent.parent
PROJECT_PATH = APP_PATH.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True, cast=bool)
HTTPS = env("HTTPS", default=True, cast=bool)


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "website.apps.WebsiteConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "sass_processor",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "voices.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [APP_PATH / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "voices.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_ENGINE = env("DATABASE_ENGINE", "django.contrib.gis.db.backends.spatialite")
DATABASE_NAME = env("DATABASE_NAME", PROJECT_PATH / "db.sqlite3")

DATABASES = {"default": {"ENGINE": DATABASE_ENGINE, "NAME": DATABASE_NAME}}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = env("LANGUAGE_CODE", default="en")
TIME_ZONE = env("TIME_ZONE", default="UTC")
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Used by collectstatic
STATIC_ROOT = env("STATIC_ROOT", PROJECT_PATH / ".static", cast=Path)


STATICFILES_DIRS = [APP_PATH / "static"]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "sass_processor.finders.CssFinder",
]

SASS_PROCESSOR_ROOT = STATIC_ROOT  # default is STATIC_ROOT
SASS_PROCESSOR_ENABLED = True
SASS_OUTPUT_STYLE = "compressed"  # or "expanded"

MEDIA_ROOT = env("MEDIA_ROOT", default=PROJECT_PATH / ".media", cast=Path)
MEDIA_URL = "media/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DJANGO_LOG_LEVEL = env("DJANGO_LOG_LEVEL", "WARNING" if not DEBUG else "INFO")
LOGURU_LOG_LEVEL = env("LOGURU_LEVEL", "WARNING" if not DEBUG else "INFO")

_lat, _lon = env("DEFAULT_POINT", default="44.6488366 10.9200867").strip().split()
DEFAULT_POINT = Point.from_ewkt(f"POINT({float(_lat)} {float(_lon)})")

BLACKLIST_PATH = env("BLACKLIST_PATH", default="")

SPACY_MODEL_NAME = env("SPACY_MODEL_NAME", default="it_core_news_lg")
SPACY_VALID_TOKENS = (
    spacy.symbols.ADJ,
    # spacy.symbols.ADV,
    spacy.symbols.NOUN,
    spacy.symbols.NUM,
    spacy.symbols.PROPN,  # Proper noun
    spacy.symbols.VERB,
)
