"""
Django's settings for voice landscape project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

# Application definition
INSTALLED_APPS = [
    ...,
    "django_extensions",
]

# --- LOG --- #


LOG_ROOT = BASE_DIR / ".log"
LOG_ROOT.mkdir(exist_ok=True)

LOG_ROOT.mkdir(exist_ok=True)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOG_ROOT / "voices.log"),
        },
    },
    "root": {"handlers": ["file"], "level": DJANGO_LOG_LEVEL},
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        }
    },
}


# --- ALLOWED HOSTS, CORS e HTTPS --- #
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=f"localhost 127.0.0.1 [::1]").split()
if DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(DOMAIN)


# --- DEMO --- #
DEMO_PLACES_REFERENCE = config("DEMO_REFERENCE", default="sso_2023")
DEMO_SHARES_PATH = config("DEMO_SHARES_PATH", default=None)
